"""changes

Revision ID: 40289ed6f5a2
Revises: 780b5ab385af
Create Date: 2026-05-19 15:50:32.445963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40289ed6f5a2'
down_revision = '780b5ab385af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
