"""add job image_url

Revision ID: 43270745274e
Revises: 40289ed6f5a2
Create Date: 2026-05-19 22:59:52.029109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43270745274e'
down_revision = '40289ed6f5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
