"""make worker_id nullable in transactions

Revision ID: 5fd941fedfca
Revises: 96a7c0634141
Create Date: 2026-05-20 23:06:09.499651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd941fedfca'
down_revision = '96a7c0634141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
