"""add profile completed

Revision ID: 780b5ab385af
Revises: 79f8aa2b1cbf
Create Date: 2026-05-19 15:42:03.564996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780b5ab385af'
down_revision = '79f8aa2b1cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')

    # ### end Alembic commands ###
